name: Cypress Tests

# Controls when the workflow will run
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          repository: 'RavitejaBoddu/CodeCommunityApp'
          ref: 'cypress_test'
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v4.1.1
        with:
          install: npm install
          start: npm start
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
    
    
 
